module.exports = [
  'radium',
  'spectacle',
  'victory',
  'component-playground',
  'es6-interactive-guide',
  'react-shuffle',
  'builder',
  'css-to-radium',
  'pull-report',
  'chai-jq',
  'handlebones',
  'ecology',
  'rowdy',
  'express-winston-middleware',
  'gulp-mdox',
  'mock-raf',
  'requirepack'
];